version: '3'
services:
  php56_sorteio_amigo_secreto:
    image: "php:5.6-apache"
    ports:
      - 8856:80
    volumes:
      - ./:/var/www/html/
    depends_on:
      - mysql_sorteio_amigo_secreto
  mysql_sorteio_amigo_secreto:
    image: "mysql:5.5"
    ports:
      - 3306:3306
    volumes:
      - ./database/sql/:/home/
      - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
  composer_sorteio_amigo_secreto:
    image: "composer"
    volumes:
      - ./:/app
    depends_on:
      - php56_sorteio_amigo_secreto
    command: composer install
