<?php
return array(
    'home'=>array(
        'neededClass'=>'Home',
        'archive'=>'Home.php',
        'needSSL'=>false,
        'needLogin'=>false,
        'isAJAX'=>false,
        'baseTemplate'=>'BaseTemplate.php',
        'menu'=>'BaseMenu.php',
        'errorTemplate'=>'BaseErrorTemplate.php',
        'includePage'=>'home.php',
        'successRedirect'=>null,
        'error'=>'_ErrorDefault.php',
        'permissao'=>'ALL'
    ),
    'logout'=>array(
        'neededClass'=>'Logout',
        'archive'=>'Login.php',
        'needSSL'=>true,
        'needLogin'=>true,
        'isAJAX'=>false,
        'baseTemplate'=>'BaseTemplate.php',
        'menu'=>'BaseMenu.php',
        'errorTemplate'=>'BaseErrorTemplate.php',
        'includePage'=>'home.php',
        'successRedirect'=>'home',
        'error'=>'_ErrorDefault.php',
        'permissao'=>'ALL'
    ),
    'logon'=>array(
        'neededClass'=>'Logon',
        'archive'=>'Login.php',
        'needSSL'=>true,
        'needLogin'=>false,
        'isAJAX'=>false,
        'baseTemplate'=>'BaseTemplate.php',
        'menu'=>'BaseMenu.php',
        'errorTemplate'=>'BaseErrorTemplate.php',
        'includePage'=>'home.php',
        'successRedirect'=>'inicio',
        'error'=>'_ErrorDefault.php',
        'permissao'=>'ALL'
    ),
    'inicio'=>array(
        'neededClass'=>'Inicio',
        'archive'=>'Inicio.php',
        'needSSL'=>true,
        'needLogin'=>true,
        'isAJAX'=>false,
        'baseTemplate'=>'BaseTemplate.php',
        'menu'=>'BaseMenu.php',
        'errorTemplate'=>'BaseErrorTemplate.php',
        'includePage'=>'inicio.php',
        'successRedirect'=>null,
        'error'=>'_ErrorDefault.php',
        'permissao'=>'ALL'
    ),
);
